name: Build and Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - "**"

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests -sv --doctest-modules --junitxml=junit/test-results.xml

      - name: Upload pytest results
        uses: actions/upload-artifact@v4.5.0
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          comment_mode: off
          files: junit/test-results.xml

  build-and-publish-package:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools_scm
      - name: Build package
        run: python -m build
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/helm_image_updater-*.tar.gz"
          allowUpdates: true
          replacesArtifacts: true
          generateReleaseNotes: true
