name: "helm-image-updater-testing e2e tests"
run-name: "Testing branch: ${{ github.ref_name }}"

on:
  push:
    branches: ['**']  # Test all branches
    paths:
      - 'helm_image_updater/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements.txt'
      - 'action.yaml'

jobs:
  test-branch:
    name: "Run Test Suite for ${{ github.ref_name }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1.11.0
        with:
          app-id: "1032649"  # Same app used in the main helm-image-updater
          private-key: ${{ secrets.GITOPS_KBC_STACKS_ACTIONS_APP_PVK }}
          owner: keboola
          repositories: "helm-image-updater-testing"

      - name: Trigger and wait for test suite
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "🚀 Triggering test suite for branch: $BRANCH_NAME"

          # Trigger the external test workflow
          gh workflow run "test-suite.yaml" \
            --repo keboola/helm-image-updater-testing \
            --field helm-image-updater-branch="$BRANCH_NAME"

          echo "⏳ Waiting for workflow to start..."
          sleep 10

          # Find the latest workflow run for our branch
          WORKFLOW_RUN_ID=$(gh run list \
            --repo keboola/helm-image-updater-testing \
            --workflow="test-suite.yaml" \
            --json databaseId,headBranch,status,conclusion,createdAt \
            --jq "map(select(.headBranch == \"main\" or .headBranch == null)) | sort_by(.createdAt) | reverse | .[0].databaseId")

          if [ -z "$WORKFLOW_RUN_ID" ] || [ "$WORKFLOW_RUN_ID" = "null" ]; then
            echo "❌ Could not find the triggered workflow run"
            exit 1
          fi

          echo "🔗 Workflow Run ID: $WORKFLOW_RUN_ID"
          echo "📊 View progress: https://github.com/keboola/helm-image-updater-testing/actions/runs/$WORKFLOW_RUN_ID"

          # Wait for completion with timeout (max 20 minutes)
          MAX_WAIT=1200  # 20 minutes
          WAIT_TIME=0
          POLL_INTERVAL=30  # Check every 30 seconds

          echo "⏳ Waiting for test suite completion (max 20 minutes)..."

          while [ $WAIT_TIME -lt $MAX_WAIT ]; do
            STATUS_INFO=$(gh run view $WORKFLOW_RUN_ID \
              --repo keboola/helm-image-updater-testing \
              --json status,conclusion)

            STATUS=$(echo "$STATUS_INFO" | jq -r '.status')
            CONCLUSION=$(echo "$STATUS_INFO" | jq -r '.conclusion')

            echo "⏱️  Status: $STATUS, Conclusion: $CONCLUSION (waited ${WAIT_TIME}s)"

            if [ "$STATUS" = "completed" ]; then
              echo ""
              echo "🏁 Test suite completed!"
              echo "📊 Final results: https://github.com/keboola/helm-image-updater-testing/actions/runs/$WORKFLOW_RUN_ID"

              if [ "$CONCLUSION" = "success" ]; then
                echo "✅ All tests PASSED!"
                echo ""
                echo "## 🎉 Test Suite Results"
                echo "- **Branch Tested:** \`$BRANCH_NAME\`"
                echo "- **Status:** ✅ **SUCCESS**"
                echo "- **Repository:** keboola/helm-image-updater-testing"
                echo "- **Workflow Run:** [$WORKFLOW_RUN_ID](https://github.com/keboola/helm-image-updater-testing/actions/runs/$WORKFLOW_RUN_ID)"
                exit 0
              else
                echo "❌ Tests FAILED with conclusion: $CONCLUSION"
                echo ""
                echo "## 💥 Test Suite Results"
                echo "- **Branch Tested:** \`$BRANCH_NAME\`"
                echo "- **Status:** ❌ **FAILED** ($CONCLUSION)"
                echo "- **Repository:** keboola/helm-image-updater-testing"
                echo "- **Workflow Run:** [$WORKFLOW_RUN_ID](https://github.com/keboola/helm-image-updater-testing/actions/runs/$WORKFLOW_RUN_ID)"
                echo ""
                echo "Please check the external workflow for detailed failure information."
                exit 1
              fi
            fi

            sleep $POLL_INTERVAL
            WAIT_TIME=$((WAIT_TIME + POLL_INTERVAL))
          done

          echo "⏰ Test suite timed out after 20 minutes"
          echo "❌ **TIMEOUT** - Tests did not complete within the maximum wait time"
          echo "🔗 Check status manually: https://github.com/keboola/helm-image-updater-testing/actions/runs/$WORKFLOW_RUN_ID"
          exit 1